### ISSUE TITLE
about bug

### ISSUE THREAD

**Issue by huixiancheng** [wjy199708/my_point_painting#1]
have you train it sucessfully?however ,i meet some troubles.
The bug is:
point_scores = class_scores[points_projected_on_mask[:,1],points_projected_on_mask[:, 0]]
.reshape(-1, 1).double()
IndexError: tensors used as indices must be long, byte or bool tensors
could you help me slove,ths 👍

**Comment by huixiancheng** [comment]
I take a little test like:
import torch
class_scores = torch.randn(375,1242)
points_projected_on_mask = torch.randn(38121,3)
print(class_scores,points_projected_on_mask)
point_scores = class_scores[points_projected_on_mask[:, 1], points_projected_on_mask[:, 0]].reshape(-1, 1).double()
print(point_scores)

there also same error,so i think there wrong in the line215 of the dataset.py
could you provide some helps :-)

**Comment by wjy199708** [comment]
okay, what`s is your pytorch version.
If you still can not solve the problem,i wish you can install  pytorch==1.5.0.










在 2020-11-22 20:20:17，"普通小程" <notifications@github.com> 写道：

have you train it sucessfully?however ,i meet some troubles.
The bug is:
point_scores = class_scores[points_projected_on_mask[:,1],points_projected_on_mask[:, 0]]
.reshape(-1, 1).double()
IndexError: tensors used as indices must be long, byte or bool tensors
could you help me slove,ths

**Comment by wjy199708** [comment]
@huixiancheng 
for now, the file of 'eval.py' still has something problem, but I am trying to fix it.

**Comment by huixiancheng** [comment]
thx for reply. the env is torch1.50 with torchvision0.60 without cuda
however,when i revise the dataset.py as follows
from line211：
        points_projected_on_mask = torch.from_numpy(points_projected_on_mask[:, :2]).type(torch.long) 
        class_scores = class_scores.type(torch.long)
        point_scores = class_scores[points_projected_on_mask[:, 1],
                                    points_projected_on_mask[:, 0]].reshape(-1, 1).double()
        augmented_lidar_cam_coords = torch.cat((lidar_cam_coords[:, :-1].to(
            self.device), reflectances.to(self.device), point_scores.to(self.device)), 1)
the train.py run successfully
Samples processed for this epoch: 100 / 6012 Average Loss so far this epoch is: 16.676673114299774
Samples processed for this epoch: 200 / 6012 Average Loss so far this epoch is: 12.612602808037582
Samples processed for this epoch: 300 / 6012 Average Loss so far this epoch is: 10.593285953676379
Samples processed for this epoch: 400 / 6012 Average Loss so far this epoch is: 9.280735548096473
but i didn't know is it truly right for this model.

**Comment by ZhangYu1ing** [comment]
Hi, did the eval.py work successfully for you?

**Comment by huixiancheng** [comment]
not. I have give up this pipeline since it since it has a lot of strange errors and missing notes
